  swetrix:
    image: swetrix/swetrix-fe:v5.2.1
    restart: always
    depends_on:
      - swetrix-api
    environment:
      - BASE_URL=${BASE_URL}
    # Enklare healthcheck för react-router-serve
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:3000/ || exit 1"]
      interval: 15s
      timeout: 10s
      start_period: 80s   # Ge den mer tid att starta
      retries: 12
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.swetrix.rule=Host(`swetrix.vivemo.se`)"
      - "traefik.http.routers.swetrix.entrypoints=websecure"
      - "traefik.http.routers.swetrix.tls.certresolver=letsencrypt"
      - "traefik.http.services.swetrix.loadbalancer.server.port=3000"
      
